version: 2
updates:
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Github Actions
  - package-ecosystem: "github-actions
    directory: "/"
    schedule:
      interval: "weekly"