_extends: .github

repository:
    description: 💻 Template for quickly spawning new go cli application with the basic CI pipelines.
    homepage: https://github.com/KarolosLykos/cli-template
    topics: go, golang, template, cli, cobra, viper
    private: false
    
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks: null
      required_linear_history: true
      enforce_admins: null
      restrictions: null
