version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - "github.com/spf13/cobra"
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - -ST1006
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocritic
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/KarolosLykos/cli-template
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
