name: golangci-lint
on: [ push, pull_request ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.43
