name: Initialize

on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run initialization
        run: |
          go get
          go mod tidy
          go run ./setup/main.go
      - name: Create Pull Request
        run: |
          git config --global user.name YOUR_NAME
          git config --global user.email YOUR_EMAIL
          git commit -am "Automated report"
          git push